services:

    rpg.example.sum:
      class: RPGBundle\Service\SumService

    default_controller:
      class: RPGBundle\Controller\DefaultController
      autowire: true

    player_controller:
      class: RPGBundle\Controller\PlayerController
      autowire: true

    test_command:
      class: RPGBundle\Command\TestCommand
      tags:
        - {name: console.command}


    player.service:
        class: RPGBundle\Service\PlayerService
