services:
    api_key_user_provider:
      class: RPGBundle\Security\ApiKeyUserProvider
      autowire: true

    api_key_authenticator:
      class: RPGBundle\Security\ApiKeyAuthenticator

    rpg.example.sum:
      class: RPGBundle\Service\SumService

    player_controller:
      class: RPGBundle\Controller\PlayerController
      autowire: true

    test_command:
      class: RPGBundle\Command\TestCommand
      tags:
        - {name: console.command}

    player.service:
        class: RPGBundle\Service\PlayerService
        autowire: true

    map.service:
        class: RPGBundle\Service\MapService
        autowire: true

    score.service:
        class: RPGBundle\Service\ScoreService
        autowire: true

    map.destroyed_tile.event_listener:
        class: RPGBundle\EventListener\MapTileDestroyedEventListener
        autowire: true
        tags:
            - { name: kernel.event_listener, event: map.tile.destroyed, method: onTileDestroyed }

    map.all_tiles_destroyed.event_listener:
        class: RPGBundle\EventListener\MapAllTilesDestroyedEventListener
        autowire: true
        tags:
            - { name: kernel.event_listener, event: map.destroyed, method: onAllTilesDestroyed }

    level_up.event_listener:
        class: RPGBundle\EventListener\LevelUpEventListener
        autowire: true
        tags:
            - { name: kernel.event_listener, event: level.up, method: onLevelUp }
